shaping of array
reshape(inplace, in memory) , shape, resize(insize)


In [2]:
import numpy as np
arr = np.arange(10).reshape(5,2)
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

# 3D Slicing


In [3]:
arr =np.arange(1,25).reshape(2,3,4)

In [4]:
arr


array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [8]:
# arr[1,[0,2],0:3:2]
arr[1,[0,2],0:3:2]

array([[13, 15],
       [21, 23]])

In [42]:
arr1 = np.arange(100).reshape(4,5,5)
arr1

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74]],

       [[75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [43]:
arr1[2:4,:,:]

array([[[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74]],

       [[75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [45]:
import pandas as p

In [49]:
obj = p.Series([2,33,4,5,66,77])
obj  #index    values


0     2
1    33
2     4
3     5
4    66
5    77
dtype: int64

In [72]:
obj1 = p.Series([2,33,4,5,66,77,81], index= ['a','b','c','d','e','f','g'])
obj1['a']

2

In [77]:
print(obj1>10)
print()
print(obj1[obj1>5])

a    False
b     True
c    False
d    False
e     True
f     True
g     True
dtype: bool

b    33
e    66
f    77
g    81
dtype: int64


# DataFrames

In [6]:
import pandas as p
data = {'state': ['Karachi', 'Islamabad', 'Peshawar', 'Faisalabad', 'Quetta'],
'year': [2000, 2001, 2002, 2001, 2002],
"pop":[1.1, 2.2, 3.3, 4.4, 5.5],}
frame = p.DataFrame(data)
frame

state  year  pop
0     Karachi  2000  1.1
1   Islamabad  2001  2.2
2    Peshawar  2002  3.3
3  Faisalabad  2001  4.4
4      Quetta  2002  5.5

In [12]:
frame.head(2)


state  year  pop
0    Karachi  2000  1.1
1  Islamabad  2001  2.2

In [13]:
frame.tail(2)

state  year  pop
3  Faisalabad  2001  4.4
4      Quetta  2002  5.5

In [17]:
frame = p.DataFrame(data, columns=["year","state","pop"])
frame


year       state  pop
0  2000     Karachi  1.1
1  2001   Islamabad  2.2
2  2002    Peshawar  3.3
3  2001  Faisalabad  4.4
4  2002      Quetta  5.5

In [26]:
frame = p.DataFrame(data, columns=["year","state","pop","debt"], index=['one','two','three','four',"five"])
frame

year       state  pop debt
one    2000     Karachi  1.1  NaN
two    2001   Islamabad  2.2  NaN
three  2002    Peshawar  3.3  NaN
four   2001  Faisalabad  4.4  NaN
five   2002      Quetta  5.5  NaN

In [28]:
frame["debt"]= range(1,6)
frame

year       state  pop  debt
one    2000     Karachi  1.1     1
two    2001   Islamabad  2.2     2
three  2002    Peshawar  3.3     3
four   2001  Faisalabad  4.4     4
five   2002      Quetta  5.5     5

In [38]:
frame.loc["one":"three":2] #last range is included

year     state  pop  debt
one    2000   Karachi  1.1     1
three  2002  Peshawar  3.3     3

In [40]:
frame.iloc[0:3:2]   #last range is included

year     state  pop  debt
one    2000   Karachi  1.1     1
three  2002  Peshawar  3.3     3

In [32]:
val = p.Series([-1,2,3], index=["one","three","five"])
val

one     -1
three    2
five     3
dtype: int64

In [43]:
frame["debt"]= val
frame

year       state  pop  debt
one    2000     Karachi  1.1  -1.0
two    2001   Islamabad  2.2   NaN
three  2002    Peshawar  3.3   2.0
four   2001  Faisalabad  4.4   NaN
five   2002      Quetta  5.5   3.0

In [53]:
frame["eastern"]= frame.state=="Karachi"
frame

year       state  pop  debt  eastern
one    2000     Karachi  1.1  -1.0     True
two    2001   Islamabad  2.2   NaN    False
three  2002    Peshawar  3.3   2.0    False
four   2001  Faisalabad  4.4   NaN    False
five   2002      Quetta  5.5   3.0    False

In [67]:
PersonalStuff = {'Name': ['Husain', 'Hatim', 'Murtaza', 'Ali', 'Mustafa','Sakina'],
'Age': [19, 20, 23, 22, 220, 40],
"Gender":["male", "male","male","male","male","female"],}
Friendframe = p.DataFrame(PersonalStuff, index=["one","two","three","four","five","six"])
Friendframe

Name  Age  Gender
one     Husain   19    male
two      Hatim   20    male
three  Murtaza   23    male
four       Ali   22    male
five   Mustafa  220    male
six     Sakina   40  female

In [70]:
Friendframe["Valid_Age"]= [True if i<100 else False for i in Friendframe.Age]
Friendframe

SyntaxError: invalid syntax (<ipython-input-70-265871417b5d>, line 1)