In [1]:
import numpy as np

In [2]:
arr =  np.arange(1,25).reshape(6,4)

In [3]:
print(arr)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [5]:
arr1=arr[3:5, 0:2]
arr1

array([[13, 14],
       [17, 18]])

In [6]:
arr2=arr[:,2:3]
arr2

array([[ 3],
       [ 7],
       [11],
       [15],
       [19],
       [23]])

In [52]:
arr3= arr[[2,5],1:3 ]
arr3

array([[10, 11],
       [22, 23]])

In [54]:
arr4= arr[[2,5],[1,2]]
arr4

array([10, 23])

In [7]:
array = np.array(["murtaza", "husain", "Hatim", "husain"])
data = np.random.randint(0,100,[4,6])
data

array([[75, 35, 10, 55, 12, 45],
       [ 9, 93, 62, 93, 66, 21],
       [27, 12, 40,  8, 71, 11],
       [ 5, 44, 42, 22, 58, 63]])

In [76]:
array

array(['murtaza', 'husain', 'Hatim', 'husain'], dtype='<U7')

In [77]:
data

array([[32, 49,  9, 75, 22, 92],
       [13, 65, 76, 66, 73, 77],
       [21, 55, 52, 69, 65, 25],
       [93, 96, 66, 18, 68, 68]])

In [78]:
array=="husain"

array([False,  True, False,  True])

In [79]:
data[array=="husain", 2:]   # all rows of true index and specified column data.

array([[76, 66, 73, 77],
       [66, 18, 68, 68]])

In [80]:
data[data>7]

array([32, 49,  9, 75, 22, 92, 13, 65, 76, 66, 73, 77, 21, 55, 52, 69, 65,
       25, 93, 96, 66, 18, 68, 68])

In [93]:
arr = np.arange(25).reshape(5,5)

In [101]:
arr[[0,0,2,2] ,[2,3,2,3]]
#arr[[0,2]][:,2:4]  #fancy indexing is deep copy means seperate array is created

array([[ 2,  3],
       [12, 13]])

In [95]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [97]:
arr5 = arr[[1,4,2,3]][:,[0,4,3]]
arr5

array([[ 5,  9,  8],
       [20, 24, 23],
       [10, 14, 13],
       [15, 19, 18]])

In [103]:
array1 = np.array([[1,2,3],[4,5,6]])
array2= np.array([[7,8,9],[10,11,12]])

In [106]:
np.concatenate((array1,array2),axis=1)   #axis 1 --> increase in column

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [108]:
np.concatenate((array1,array2),axis=0)   #axis 0 --> increase in rows

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [109]:
np.size(dir(np))

622

In [115]:
ArrToSplit = np.arange(16).reshape(4,4)
ArrToSplit

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [119]:
print(np.vsplit(ArrToSplit, 2))   #split in rows, vertical line will be cut horizontally

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


In [118]:
print(np.hsplit(ArrToSplit, 2))   #split in rows, vertical line will be cut horizontally

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
